#pragma once

/* SPI */
#define SPI_SCK_PIN GP22
#define SPI_MOSI_PIN GP23
#define SPI_MISO_PIN GP20

/* Pointing device */
#define PMW33XX_CS_PIN GP21 // SPI CS pin.
#define PMW33XX_CPI 800    // The CPI range is 100-12000, in increments of 100. Defaults to 1600 CPI.
#define POINTING_DEVICE_INVERT_Y
#define POINTING_DEVICE_RIGHT
#define POINTING_DEVICE_TASK_THROTTLE_MS 10
#define MOUSE_EXTENDED_REPORT

/* Split keyboard */
#define SPLIT_POINTING_ENABLE

/* RP2040 Reset. */
#define RP2040_BOOTLOADER_DOUBLE_TAP_RESET
#define RP2040_BOOTLOADER_DOUBLE_TAP_RESET_LED GP17

//#define BOOTMAGIC_ROW_RIGHT 6
//#define BOOTMAGIC_COLUMN_RIGHT 0
